### ISSUE TITLE
variable will be reported as unused when it is used only in regexp

### ISSUE THREAD

**Issue by chylli** [doherty/Dist-Zilla-Plugin-Test-UnusedVars#8]
`$t` will be reported as 'unused' in this example:

```
sub a{
  my $t = "abc";
  $t =~ /(.*)c/;
  return $1;
}
```

**Comment by karenetheridge** [comment]
All the action happens in Test::Vars -- you'll want to submit the bug there.  The dzil plugin just generates a test file around it.
